---
language: node_js
node_js:
  - "0.12"
  - "4"
  - "5"

sudo: required
dist: trusty  

cache:
  directories:
    - node_modules

before_install:
  - sudo apt-get install zip
  - npm config set spin false
  - npm install -g bower
  - bower --version
  - npm install phantomjs-prebuilt
  - node_modules/phantomjs-prebuilt/bin/phantomjs --version

install:
  - npm install
  - bower install

script:
  - npm test
